# Generated by Django 5.1 on 2024-08-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iphone',
            options={'verbose_name': 'Айфон', 'verbose_name_plural': 'Айфоны'},
        ),
        migrations.AlterField(
            model_name='iphone',
            name='harakter',
            field=models.TextField(verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='image',
            field=models.ImageField(upload_to='iphone_images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='iphone',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
