# Generated by Django 5.1 on 2024-08-19 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphone', '0002_alter_iphone_options_alter_iphone_harakter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='iphone',
            name='apple',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iphone.apple'),
            preserve_default=False,
        ),
    ]
