# Generated by Django 5.1 on 2024-08-19 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphone', '0003_apple_iphone_apple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphone',
            name='apple',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iphone.apple'),
        ),
    ]
