# Generated by Django 5.1 on 2024-09-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphone', '0004_alter_iphone_apple'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphone',
            name='sim_card',
            field=models.CharField(choices=[('O!', 'O!'), ('Beelin', 'Beelin'), ('MegaCom', 'MegaCom')], default=1, max_length=10, verbose_name='Сим-карта'),
            preserve_default=False,
        ),
    ]
